
import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Coffee } from 'lucide-react';

interface ResultCardProps {
  content: string;
  title?: string;
  onDonate?: () => void;
}

export const ResultCard: React.FC<ResultCardProps> = ({ content, title = "天师批注 (Oracle Log)", onDonate }) => {
  if (!content) return null;

  return (
    <div className="mt-8 border-2 border-fuchsia-500 bg-black/80 p-6 relative shadow-[0_0_15px_rgba(217,70,239,0.2)] animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="absolute top-0 left-0 bg-fuchsia-600 text-black font-bold px-3 py-1 text-sm font-mono transform -translate-y-1/2 translate-x-4">
        {title}
      </div>
      <div className="prose prose-invert prose-green max-w-none font-sans leading-relaxed">
        {/* Simple rendering of markdown-like text */}
        <div className="whitespace-pre-wrap text-gray-300">
            {content.split('\n').map((line, i) => {
                if (line.startsWith('##')) return <h3 key={i} className="text-xl font-bold text-fuchsia-400 mt-6 mb-3 border-l-4 border-fuchsia-600 pl-2">{line.replace(/#/g, '')}</h3>;
                if (line.startsWith('**')) return <strong key={i} className="text-green-400 font-bold">{line.replace(/\*\*/g, '')}</strong>;
                if (line.startsWith('- ')) return <li key={i} className="ml-4 text-gray-300 marker:text-green-600">{line.replace('- ', '')}</li>;
                return <p key={i} className="mb-2 text-justify">{line}</p>;
            })}
        </div>
      </div>
      
      <div className="mt-6 pt-4 border-t border-gray-800 flex justify-between items-center">
        <div className="text-[10px] text-gray-600 font-mono">
          GENERATED BY GEMINI 2.5 // 天机运算完成
        </div>
        
        {/* Donation Button - Secondary Location */}
        {onDonate && (
             <button 
             onClick={onDonate}
             className="flex items-center gap-1 text-xs text-yellow-600 hover:text-yellow-400 transition-colors font-mono"
           >
             <Coffee size={12} />
             <span>打赏天师 (Tip)</span>
           </button>
        )}
      </div>
    </div>
  );
};
